version: "3"
services:
  age2age:
    build: .
    # image: debian:10
    container_name: age2age
    restart: always
    ports:
      - "3000:3000"
    depends_on: 
      - db
    volumes:
      - .:/app

  db:
    image : mysql
    container_name: db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/usr/bin/mysql --user=sophie --password=sophie --execute 'SHOW DATABASES;'"]
      interval: 2s
      timeout: 20s
      retries: 10
    ports:
      - "3308:3306" 
      # - "3306:3306"
    environment : 
      MYSQL_USER: sophie
      MYSQL_ROOT_PASSWORD: sophie
      MYSQL_DATABASE: CUBE
      MYSQL_PASSWORD : sophie
    volumes : 
      - ./docker/db/data:/var/lib/mysql

