on:
  push:
    branches: 
      - recette
jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install dependencies and build
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '16.x'
  #     - run: |
  #         npm install
  #         npm run build
  build-and-push-image:
    runs-on: ubuntu-latest
    # needs: [build]
    # if: github.ref_name == 'main'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ghcr.io/sophieaccount/front_end_age2age:${{ github.ref_name }}
        env:
          host_api: "https://cube.nekshor.fr:4000"
  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push-image]
    # if: github.ref_name == 'main'
    permissions:
      contents: read
      packages: write
    steps:
      - name: SSH into the Deployement Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_ANTOINE }}
          username: ${{ secrets.SSH_USER_ANTOINE }}
          password: ${{ secrets.SSH_PASSWORD_ANTOINE }}
          script: |
            cd /home/web/recette
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull ghcr.io/sophieaccount/front_end_age2age:${{ github.ref_name }}
            docker stop recette_front || true  # Arrêter le conteneur existant s'il existe
            docker rm recette_front || true    # Supprimer le conteneur existant s'il existe
            docker-compose up -d || docker compose up -d
          #docker run -d --name recette_front -p 3000:3000 ghcr.io/sophieaccount/front_end_age2age:${{ github.ref_name }} 

          # cd /home/web/age_age
            # git set-url origin https://github.com/sophieAccount/front_end_age2age.git
            # git pull origin ${{ github.ref_name }}
            # npm install
            # docker stop age2age || true
            # docker rm age2age || true
            # docker-compose up -d



